# Warning! Watch setup guide (docs/authentik-setup.md)

services:
  postgresql:
    container_name: authentik-db
    image: postgres:16-alpine
    restart: unless-stopped

    # Networking
    networks:
      - authentik-internal

    # Filesystem
    volumes:
      - database:/var/lib/postgresql/data
    
    # Security
    security_opt:
      - no-new-privileges:true  # forbid privilege escalation
    
    # Environment
    environment:
      TZ: ${TIMEZONE:-Europe/Stockholm}

      # Service specific
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-authentik}
      POSTGRES_DB: ${PG_DB:-authentik}

    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
      - CMD-SHELL
      - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      timeout: 5s
    

      
  server:
    container_name: authentik-server
    image: ghcr.io/goauthentik/server:2026.2.0
    restart: unless-stopped
    depends_on:
      postgresql:
        condition: service_healthy
      
    command: server
    
    # Networking
    networks:
      - traefik
      - authentik-internal
    ports:
      - "9000:9000"
      - "9443:9443"
    
    # Filesystem
    volumes:
      - ./data:/data
      - ./custom-templates:/templates
    
    # Security
    security_opt:
      - no-new-privileges:true  # forbid privilege escalation
    
    # Environment
    environment:
      TZ: ${TIMEZONE:-Europe/Stockholm}

      # Service specific
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    


  worker:
    container_name: authentik-worker
    image: ghcr.io/goauthentik/server:2026.2.0
    restart: unless-stopped
    depends_on:
      postgresql:
        condition: service_healthy

    command: worker
    
    # Networking
    networks:
      - authentik-internal

    # Filesystem
    volumes:
      - ./data:/data
      - ./certs:/certs
      - ./custom-templates:/templates
    
    # Security
    security_opt:
      - no-new-privileges:true  # forbid privilege escalation

    # Environment
    environment:
      TZ: ${TIMEZONE:-Europe/Stockholm}

      # Service specific
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}

networks:
  traefik:
    external: true
  authentik-internal:
    external: false

volumes:
  database:
    driver: local
