# Verified working with rootful docker (sudo docker compose up -d)

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped

    # Networking
    ports:
      - 8096:8096 # HTTP
      - 8920:8920 # HTTPS (You need to set up SSL cert your self)

    # Filesystem
    volumes:
      - ./config:/config
      - /mnt/data/media/tv:/data/tvshows
      - /mnt/data/media/movies:/data/movies
    
    # Security
    security_opt:
      - no-new-privileges:true  # forbid privilege escalation

    # Environment
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE:-Europe/Stockholm}