# Warning! Watch setup guide before you deploy (docs/crowdsec-setup.md)

services:
  crowdsec:
    container_name: crowdsec
    image: crowdsecurity/crowdsec:v1.7.6
    restart: unless-stopped

    # Networking
    networks:
      - traefik

    # Filesystem
    volumes:
      - ./config/acquis.yaml:/etc/crowdsec/acquis.yaml
      - crowdsec-db:/var/lib/crowdsec/data/
      - crowdsec-config:/etc/crowdsec/
      - traefik_traefik-logs:/var/log/traefik/:ro
    
    # Security
    security_opt:
      - no-new-privileges:true  # forbid privilege escalation

    # Environment
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE:-Europe/Stockholm}

      # Service specific
      GID: 1000
      COLLECTIONS: "crowdsecurity/linux crowdsecurity/traefik"
    
    
    
  bouncer-traefik:
    container_name: bouncer-traefik
    image: fbonalair/traefik-crowdsec-bouncer:0.5.0 # This is old, should look for alternative
    restart: unless-stopped
    depends_on:
      - crowdsec

    # Networking
    networks:
      - traefik
    
    # Security
    security_opt:
      - no-new-privileges:true  # forbid privilege escalation
    
    # Environment
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE:-Europe/Stockholm}

      # Service specific
      CROWDSEC_BOUNCER_API_KEY: ${CROWDSEC_BOUNCER_API_KEY}
      CROWDSEC_AGENT_HOST: crowdsec:8080



networks:
  traefik:
    external: true

volumes:
  crowdsec-db:
  crowdsec-config:
  traefik_traefik-logs:
    external: true