# Warning! Watch setup on how to import dashboard (docs/grafana-setup.md)

services:
  grafana:
    container_name: grafana
    image: docker.io/grafana/grafana-oss:12.4.0
    restart: unless-stopped
    
    # Networking
    ports:
      - 3030:3000

    # Filesystem
    volumes:
      - grafana-data:/var/lib/grafana
    
    # Security
    security_opt:
      - no-new-privileges:true  # forbid privilege escalation

    # Environment
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE:-Europe/Stockholm}

      # Service specific
      GF_SECURITY_ALLOW_EMBEDDING: true
      GF_AUTH_ANONYMOUS_ENABLED: true



volumes:
  grafana-data:
    driver: local
