services:
  paperless-webserver:
    container_name: paperless-webserver
    image: ghcr.io/paperless-ngx/paperless-ngx:v2.20.8
    restart: unless-stopped
    depends_on:
      - paperless-db
      - paperless-broker
      - paperless-gotenberg
      - paperless-tika

    # Networking
    ports:
      - "8001:8000"
    
    # Filesystem
    volumes:
      - /mnt/data/paperless/data:/usr/src/paperless/data
      - /mnt/data/paperless/media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    
    # Security
    security_opt:
      - no-new-privileges:true  # forbid privilege escalation

    # Environment
    environment:
      # Service specific
      USERMAP_UID: ${USERMAP_UID:-1000}
      USERMAP_GID: ${USERMAP_GID:-1000}
      PAPERLESS_TIME_ZONE: ${PAPERLESS_TIME_ZONE:-Europe/Stockholm}
      PAPERLESS_SECRET_KEY: ${PAPERLESS_SECRET_KEY}
      PAPERLESS_OCR_LANGUAGE: ${PAPERLESS_OCR_LANGUAGE}
      PAPERLESS_OCR_LANGUAGES: ${PAPERLESS_OCR_LANGUAGES}
      PAPERLESS_URL: ${PAPERLESS_URL}
      PAPERLESS_REDIS: redis://paperless-broker:6379
      PAPERLESS_DBHOST: paperless-db
      PAPERLESS_DBNAME: paperless
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS: ${POSTGRES_PASSWORD}
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://paperless-gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://paperless-tika:9998




  paperless-broker:
    container_name: paperless-broker
    image: library/redis:8
    restart: unless-stopped

    # Filesystem
    volumes:
      - paperless-broker:/data
    
    # Security
    security_opt:
      - no-new-privileges:true  # forbid privilege escalation
    
    # Environment
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE:-Europe/Stockholm}



  paperless-db:
    container_name: paperless-db
    image: library/postgres:18
    restart: unless-stopped

    # Filesystem
    volumes:
      - paperless-db:/var/lib/postgresql/data
    
    # Security
    security_opt:
      - no-new-privileges:true  # forbid privilege escalation

    # Environment
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE:-Europe/Stockholm}

      # Service specific
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}



  
  paperless-gotenberg:
    container_name: paperless-gotenberg
    image: gotenberg/gotenberg:8.27
    restart: unless-stopped

    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

    # Security
    security_opt:
      - no-new-privileges:true  # forbid privilege escalation
    
    # Environment
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE:-Europe/Stockholm}

  


  paperless-tika:
    container_name: paperless-tika
    image: apache/tika:3.2.3.0
    restart: unless-stopped

    # Security
    security_opt:
      - no-new-privileges:true  # forbid privilege escalation
    
    # Environment
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE:-Europe/Stockholm}



volumes:
  paperless-db:
  paperless-broker: