services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun:v3.41
    restart: unless-stopped

    # Networking
    ports:
      - 8080:8080 # SABnzbd
      - 9696:9696 # Prowlarr
      - 8989:8989 # Sonarr
      - 7878:7878 # Radarr
      - 6767:6767 # Bazarr

    # Filesystem
    volumes:
      - ./gluetun/config:/gluetun
    devices:
      - /dev/net/tun:/dev/net/tun
    
    # Security
    security_opt:
      - no-new-privileges:true
    cap_add:
      - NET_ADMIN
      
    # Environment
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE:-Europe/Stockholm}

      # Service specific
      VPN_SERVICE_PROVIDER: ${VPN_SERVICE_PROVIDER}
      SERVER_CITIES: ${SERVER_CITIES}
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY} # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/mullvad.md
      WIREGUARD_ADDRESSES: ${WIREGUARD_ADDRESSES}
      UPDATER_PERIOD: 24h


  
  sabnzbd:
    container_name: sabnzbd
    image: lscr.io/linuxserver/sabnzbd:4.5.5
    restart: unless-stopped
    depends_on:
      - gluetun

    # Networking
    network_mode: "service:gluetun"

    # Filesystem
    volumes:
      - ./sabnzbd/config:/config
      - /mnt/data/usenet:/data/usenet:rw
    
    # Security
    security_opt:
      - no-new-privileges:true

    # Environment
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE:-Europe/Stockholm}

  
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:2.3.0
    restart: unless-stopped
    depends_on:
      - sabnzbd

    # Networking
    network_mode: "service:gluetun"

    # Filesystem
    volumes:
      - ./prowlarr/config:/config
    
    # Security
    security_opt:
      - no-new-privileges:true

    # Environment
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE:-Europe/Stockholm}

  
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:6.0.4
    restart: unless-stopped
    depends_on:
      - prowlarr
      - sabnzbd

    # Networking
    network_mode: "service:gluetun"

    # Filesystem
    volumes:
      - ./radarr/config:/config
      - /mnt/data:/data
    
    # Security
    security_opt:
      - no-new-privileges:true

    # Environment
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE:-Europe/Stockholm}

  
  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:4.0.16
    restart: unless-stopped
    depends_on:
      - prowlarr
      - sabnzbd

    # Networking
    network_mode: "service:gluetun"

    # Filesystem
    volumes:
      - ./sonarr/config:/config
      - /mnt/data:/data
    
    # Security
    security_opt:
      - no-new-privileges:true

    # Environment
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE:-Europe/Stockholm}

    
  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:1.5.6
    restart: unless-stopped
    depends_on:
      - gluetun

    # Networking
    network_mode: "service:gluetun"
    
    # Filesystem
    volumes:
      - ./bazarr/config:/config
      - /mnt/data/media:/data/media
    
    # Security
    security_opt:
      - no-new-privileges:true

    # Environment
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE:-Europe/Stockholm}
