services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:1.35.4
    restart: unless-stopped

    # Networking
    ports:
      - 8000:80
    
    # Filesystem
    volumes:
      - ./data:/data
    
    # Security
    security_opt:
      - no-new-privileges:true  # forbid privilege escalation

    # Environment
    environment:
      TZ: ${TIMEZONE:-Europe/Stockholm}

      # Service specific
      DOMAIN: https://${VAULTWARDEN_HOSTNAME}

    

    